[package]
name = "code_time_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = "3.2"
serde = "1.0.188"
futures = "0.3.28"
tokio = {version = "1.32.0", features = ["full"]}
regex = "1"
