[package]
name = "code_time_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = "3.2.2"
serde = "1.0.219"
futures = "0.3.31"
tokio = {version = "1.44.0", features = ["full"]}
regex = "1.11.1"
